# Common config
services:
  client:
    build:
      context: client/
    depends_on:
      - dopami
  dopami:
    build:
      context: dopami/
    depends_on:
      - db
    networks:
      - main
    ports:
      - 9002:9002
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    networks:
      - main

networks:
  main:
    driver: bridge
