# Production-specific config
services:
  client:
    build:
      target: prod
    volumes:
      - static:/app/dist
  dopami:
    build:
      target: prod
  nginx:
    build:
      context: nginx/
    restart: unless-stopped
    depends_on:
      - client
      - dopami
    networks:
      - main
    ports:
      - 80:80
    volumes:
      - static:/static

volumes:
  static:
    external: false
