# Production-specific config
services:
  client:
    build:
      target: prod
    volumes:
      - static:/app/dist
  dopami:
    build:
      target: prod
  nginx:
    build:
      context: nginx/
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - client
      - dopami
      - certbot
    networks:
      - main
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/static:ro
      - letsencrypt:/etc/letsencrypt:ro
  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
    command: certbot certonly --webroot -w /etc/letsencrypt/www -d dopami.me
    # command: certbot certonly -d dopami.me --dry-run
    # command: certbot renew

volumes:
  static:
    external: false
  letsencrypt:
    external: false
