# Production-specific config
services:
  client:
    build:
      target: prod
    volumes:
      - static:/app/dist
  dopami:
    build:
      target: prod
  nginx:
    build:
      context: nginx/
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - client
      - dopami
    networks:
      - main
    ports:
      - 80:80
      - 443:443
    volumes:
      - static:/static:ro
      - acmechallenge:/var/www/certbot:ro
      - letsencrypt:/etc/letsencrypt:ro
  certbot:
    image: certbot/certbot
    volumes:
      - acmechallenge:/var/www/certbot
      - letsencrypt:/etc/letsencrypt
    command: certonly --register-unsafely-without-email --agree-tos --webroot -w /var/www/certbot/ -d dopami.me
    # command: certbot certonly -d dopami.me --dry-run
    # command: certbot renew

volumes:
  static:
    external: false
  acmechallenge:
    external: false
  letsencrypt:
    external: false
